"""1

Revision ID: a7ab4f82f9ed
Revises: c5922bf7f656
Create Date: 2024-07-15 03:10:08.077899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ab4f82f9ed'
down_revision: Union[str, None] = 'c5922bf7f656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apps', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apps', 'description',
               existing_type=sa.String(length=4096),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
